# Phase 3 — Data Cleaning

In [6]:
import pandas as pd

# Load the cleaned data from Data_Understanding.ipynb
df = pd.read_csv("cleaned_data.csv")

# Convert date columns to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# Display basic info
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

*Final Step of Data Cleaning Phase*

We will create a Year column from the order date.
This will help us analyze sales trends over time later.

In [7]:
df["Order Year"] = df["Order Date"].dt.year

In [8]:
df[["Order Date","Order Year"]].head()

  Order Date  Order Year
0 2016-11-08        2016
1 2016-11-08        2016
2 2016-06-12        2016
3 2015-10-11        2015
4 2015-10-11        2015

In [9]:
# Save the cleaned dataframe for use in other notebooks
df.to_csv("cleaned_data_for_EDA.csv", index=False)
print("Data saved to cleaned_data_for_EDA.csv")

Data saved to cleaned_data_for_EDA.csv